name: Build 

on:
  push:
    branches: [ master, 'feature/*', 'bugfix/*' ]
    tags: [ 'v*' ]
  
  pull_request_target:
    branches: [ master, 'feature/*', 'bugfix/*' ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        python -m pip install git+https://github.com/pylover/cpp-coveralls.git
        git clone https://github.com/pylover/http-parser.git
        sudo make -C http-parser install
        git clone https://github.com/Snaipe/Mimick.git mimick
        mkdir mimick/build
        cmake -S mimick -B mimick/build ..
        sudo make -C mimick/build install
        sudo ldconfig /usr/local/lib
        sudo apt install libcurl4-gnutls-dev lcov
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build, Run tests, Submit coverage result
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: make clean cover
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.info
